### ISSUE TITLE
Bayestar Dust Map retrieval issue

### ISSUE THREAD

**Issue by kostas-panagiotakis** [TomWagg/cogsworth#139] opened 2024-10-07 14:28 UTC
Hi! I am using this code snippet from your documentation:

import os
import dustmaps.bayestar
from dustmaps.std_paths import data_dir
bayestar_path = os.path.join(data_dir(), 'bayestar', '{}.h5'.format("bayestar2019"))
if not os.path.exists(bayestar_path):
    dustmaps.bayestar.fetch()

And I get this error:

<img width="1087" alt="Screenshot 2024-10-07 at 3 26 31 PM" src="https://github.com/user-attachments/assets/58b56ba0-8bc2-4754-81db-27a555c3974d">

And I cannot run:

# Now call the get_observables function
p.get_observables(filters=["G", "BP", "RP"], ignore_extinction=False, assume_mw_galactocentric=True)

as: FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/path/to/store/maps/in/bayestar/bayestar2019.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Do you know how to fix this issue?

Thank you!

Best,

Kostas

**Comment by TomWagg** [comment] 2024-10-07 18:08
Hi Kostas!

Thanks for the issue - it looks like this is a problem with `dustmaps` directly, I see that [someone else has the same issue as you](https://github.com/gregreen/dustmaps/issues/54). I'm not sure how to fix it but perhaps you could comment on the issue that I linked and explain how to reproduce the error.

It'll be helpful if you explain to them your OS, which version of dustmaps/python you're running and the code snippet you used.

I'm going to close this for now since it's an external issue but let me know if the dustmaps folks recommend we change this code in any way.

Cheers,
Tom

**Closed by TomWagg** 2024-10-07 18:08 UTC
Labels: question
